host: localhost:8090
info:
  contact:
    email: support@pixiu.io
    name: API Support
    url: https://github.com/caoyingjunz/pixiu
  description: Use the Pixiu APIs to your cloud
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://github.com/caoyingjunz/pixiu
  title: Pixiu API Documentation
  version: "1.0"
paths: {}
swagger: "2.0"
