# Copyright 2021 The Pixiu Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "pixiu.labels" . | nindent 4 }}
      {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
      {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
      {{- end }}
  name: {{ template "pixiu.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    default:
      listen: {{ .Values.default.listen }}
      log_type: {{ .Values.default.log_type  }}
      log_level: {{ .Values.default.log_level  }}
      log_dir: {{ .Values.default.log_dir  }}
      jwt_key: {{ .Values.default.jwt_key  }}
    mysql:
      host: {{ .Values.mysql.host  }}
      user: {{ .Values.mysql.user  }}
      password: {{ .Values.mysql.password  }}
      port: {{ .Values.mysql.port  }}
      name: {{ .Values.mysql.name  }}
    cicd:
      driver: {{ .Values.cicd.driver  }}
      jenkins:
        host: {{ .Values.cicd.host  }}
        user: {{ .Values.cicd.user  }}
        password: {{ .Values.cicd.password  }}    
