FROM golang:1.17 as pixiu-builder
WORKDIR /app
ARG VERSION
ENV GOPROXY=https://goproxy.cn
COPY . .
RUN CGO_ENABLED=0 go build -ldflags "-s -w -X 'main.version=${VERSION}'" -o pixiu ./cmd

FROM node:16.18.0-alpine as builder
WORKDIR /build
RUN git clone https://github.com/pixiu-io/dashboard.git
RUN cd dashboard && npm install && npm run build

FROM jacky06/static:nonroot
LABEL MAINTAINER="caoyingjunz"

COPY --from=pixiu-builder /app/pixiu /app
COPY --from=builder /build/dashboard/dist /static
CMD ["/app"]
