FROM golang:1.25-alpine AS builder
WORKDIR /app
ARG VERSION
ENV GOPROXY=https://goproxy.cn
COPY go.mod go.sum ./
COPY . .
RUN CGO_ENABLED=0 go build -ldflags "-s -w -X 'main.version=${VERSION}'" -o deploy-agent ./cmd/deploy-agent

FROM alpine:3.20
LABEL MAINTAINER="PIXIU"
RUN apk add --no-cache ca-certificates tzdata
COPY --from=builder /app/deploy-agent /usr/local/bin/deploy-agent
ENTRYPOINT ["deploy-agent"]
