default:
  # 自动创建指定模型的数据库表结构，不会更新已存在的数据库表
  auto_migrate: true

  # 超级管理初始化用户名和密码；不指定的情况下，默认为 admin/Pixiu123456!
  admin_user: admin
  admin_password: Pixiu123456!

# 数据库地址信息, 根据实际情况配置
mysql:
  host: mysql # 数据库的ip
  user: root
  password: Pixiu868686
  port: 3306
  name: pixiu
